/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2018-12-10 07:06:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".headpart {\r\n");
      out.write("\tfont-family: 'Courier New', Courier, monospace;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    background-color: aqua;\r\n");
      out.write("    text-align: center; \r\n");
      out.write("    color:maroon;\r\n");
      out.write("    margin-top: -0.5%;\r\n");
      out.write("    margin-left: -0.6%;\r\n");
      out.write("    margin-right: -0.6%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mySlides {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tmargin: 2%;\r\n");
      out.write("\tmargin-left: 13%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".w3-content w3-section {\r\n");
      out.write("\tmax-width: 500px;\r\n");
      out.write("\tmax-width: height 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.desc {\r\n");
      out.write("  margin: 0%;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("  color: wheat;\r\n");
      out.write("  font-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("    background-image:url(pics/colo.jpeg) ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".home{\r\n");
      out.write("  margin-top:-2.2%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".home td:hover{\r\n");
      out.write("  border: 5px solid rgb(60, 190, 199);\r\n");
      out.write("  background-color:brown;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("  margin:-1.9%;\r\n");
      out.write("}\r\n");
      out.write(".topnav a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 15px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topnav a:hover {\r\n");
      out.write("  background-color: rgb(240, 226, 226);\r\n");
      out.write("  color: rgb(143, 88, 16);\r\n");
      out.write("}\r\n");
      out.write(".topnav a.active {\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("footer\r\n");
      out.write("{\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("}\r\n");
      out.write("/* div.gallery {\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.gallery:hover {\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.gallery img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.desc {\r\n");
      out.write("\tpadding: 15px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write("/* body {\r\n");
      out.write("\tbackground-color: lightcoral;\r\n");
      out.write("} */\r\n");
      out.write("/* footer\r\n");
      out.write("{\r\n");
      out.write("  color: #f2f2f2;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("} */\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"headpart\">\r\n");
      out.write("\t<img src=\"pics/logo1.jpg\">\r\n");
      out.write("\t<h1 align=\"center\">Welcome to Go shopping....!</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"topnav\">\r\n");
      out.write("        <a class=\"active\" href=\"#home\">Home</a>\r\n");
      out.write("        <a href=\"about.html\">About Us</a>\r\n");
      out.write("        <a href=\"login.jsp\" >Login</a>\r\n");
      out.write("        <a href=\"register.jsp\" >Register</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"w3-content w3-section\"\r\n");
      out.write("\t\tstyle=\"max-width: 200px, max-height=200px\">\r\n");
      out.write("\t\t<img class=\"mySlides\" src=\"pics/OFFER1.jpg\"  width=\"1000\" height=\"400\">\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/kids1.jpg\" width=\"1000\" height=\"400\">\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/OFF3.jpg\"  width=\"1000\" height=\"400\">\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/sunoffer.jpg\"  width=\"1000\" height=\"400\">\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/shopping.jpg\"  width=\"1000\" height=\"400\">\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/OFFER2.jpg\"  width=\"1000\" height=\"400\">  \r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/img1.jpg\"  width=\"1000\" height=\"400\" >\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/MOBILE.jpg\"  width=\"1000\" height=\"400\" >\r\n");
      out.write("     <img class=\"mySlides\" src=\"pics/men.png\"  width=\"1000\" height=\"400\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar myIndex = 0;\r\n");
      out.write("\t\tcarousel();\r\n");
      out.write("\r\n");
      out.write("\t\tfunction carousel() {\r\n");
      out.write("\t\t\tvar i;\r\n");
      out.write("\t\t\tvar x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\t\t\tfor (i = 0; i < x.length; i++) {\r\n");
      out.write("\t\t\t\tx[i].style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tmyIndex++;\r\n");
      out.write("\t\t\tif (myIndex > x.length) {\r\n");
      out.write("\t\t\t\tmyIndex = 1\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tx[myIndex - 1].style.display = \"block\";\r\n");
      out.write("\t\t\tsetTimeout(carousel, 3000); // Change image every 4 seconds\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<div class=\"home\">\r\n");
      out.write("<table border=\"1\" align=\"center\" width=100% >\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td> <a target=\"_blank\" href=\"sunglasses.jsp\"><img src=\"pics/sundisp.jpg\" width=\"650\" height=\"400\"></a>\r\n");
      out.write("        <div class=\"desc\"><h1>Sunglasses</h1></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </td>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <td> <a target=\"_blank\" href=\"Clothing.jsp\">\r\n");
      out.write("    <img src=\"pics/dress2.png\" width=100%  height=\"400\" ></a>\r\n");
      out.write("    <div class=\"desc\"><h1>Clothing</h1></div>\r\n");
      out.write("  </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td colspan=\"2\"> <a target=\"_blank\" href=\"mobile.jsp\">\r\n");
      out.write("      <img src=\"pics/md2.jpg\" width=100%  height=\"400\"></a>\r\n");
      out.write("      <div class=\"desc\"><h1>Mobile</h1></div>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  <footer>\r\n");
      out.write("      © Copyright 2014, All Rights Reserved\r\n");
      out.write("      <br>\r\n");
      out.write("      goShoppingHelp@gmail.com\r\n");
      out.write("   </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
